namespace ALMACO.UI
{
  public enum ThemeResourceKey
  {
    White,
    Dark40,
    Black,
    DarkBlue,
    CombineBlue,
    LightBlue,
    LightBlueTranslucent,
    UranianBlue,
    Eggshell,
    WarningAmber,
    GoodBlue,

    TestWeight1,
    TestWeight2,
    TestWeight3,
    TestWeight4,
    TestWeight5,

    Weight1,
    Weight2,
    Weight3,
    Weight4,
    Weight5,

    Moisture1,
    Moisture2,
    Moisture3,
    Moisture4,
    Moisture5,

    Temperature1,
    Temperature2,
    Temperature3,
    Temperature4,
    Temperature5,

    ControlDisabledOpacity,

    MinContrast,
    MaxContrast,
    Foreground,
    Background,
    MutedContrast,
    Highlight,
    MutedHighlight,
    Complement,
    BoldHighlight,
    BoldCombo,
    MutedAccent,
    ToastBackground,
    TransparentBackground,
    Logo,

    ContentForeground,
    ContentBackground,
    ContentBorder,    
    MouseOverForeground,
    MouseOverBackground,
    MouseOverBorder,
    PressedForeground,
    PressedBackground,
    PressedBorder,
    SelectedForeground,
    SelectedBackground,
    SelectedBorder,
    ActiveBackground,
    DisabledForeground,

    //GroupBoxFont,
    //GroupBoxTopBar,
    //GroupBoxFunContrastFont,
    //GroupBoxFunContrastTopBar,
    //GroupBoxBoldFont,
    //GroupBoxBoldTopBar,

    //CheckBoxForeground,
    //CheckBoxBackground,
    //CheckBoxIcon,
    //CheckBoxBorder,
    //CheckBoxMouseOverForeground,
    //CheckBoxMouseOverBackground,
    //CheckBoxMouseOverBorder,
    //CheckBoxPressedForeground,
    //CheckBoxPressedBackground,
    //CheckBoxPressedBorder,

    //ListViewForeground,
    //ListViewBackground,
    //ListViewBorder,
    //ListViewMouseOverForeground,
    //ListViewMouseOverBackground,
    //ListViewMouseOverBorder,
    //ListViewPressedForeground,
    //ListViewPressedBackground,
    //ListViewPressedBorder,

    //Heading1,
    //Heading2,
    //Heading3,
    //Link,

    //TextboxForeground,
    //TextBoxBackground,
    //TextBoxBorder,
    //TextboxMouseOverForeground,
    //TextBoxMouseOverBackground,
    //TextBoxMouseOverBorder,
    //TextboxPressedForeground,
    //TextBoxPressedBackground,
    //TextBoxPressedBorder,
    //TextBoxHighlight,

    WindowHeaderForeground,
    WindowHeaderBackground,
    WindowBackground,
    WindowHeaderMouseOverBackground,
    WindowHeaderMouseOverForeground,

    //TabItemStaticBorder,
    //TabItemStaticForeground,
    //TabItemStaticBackground,
    //TabItemContentBackground,
    //TabItemMouseOverBorder,
    //TabItemMouseOverBackground,
    //TabItemSelectedBorder,
    //TabItemSelectedBackground,
    //TabItemDisabledBorder,
    //TabItemDisabledForeground,
    //TabItemDisabledBackground,

    IconForeground,
    IconPressed,

    //ComboBoxForeground,
    //ComboBoxBackground,
    //ComboBoxBorder,
    //ComboBoxMouseOverForeground,
    //ComboBoxMouseOverBackground,
    //ComboBoxMouseOverBorder,
    //ComboBoxPressedForeground,
    //ComboBoxPressedBackground,
    //ComboBoxPressedBorder,
    //ComboBoxSelectedForeground,
    //ComboBoxSelectedBackground,
    //EditableComboBoxForeground,
    //EditableComboBoxBackground,
    //EditableComboBoxBorder,
    //EditableComboBoxMouseOverForeground,
    //EditableComboBoxMouseOverBackground,
    //EditableComboBoxMouseOverBorder,
    //EditableComboBoxPressedForeground,
    //EditableComboBoxPressedBackground,
    //EditableComboBoxPressedBorder,
    //EditableComboBoxSelectedForeground,
    //EditableComboBoxSelectedBackground,
    //EditableComboBoxHighlight,

    //RadioButtonForeground,
    //RadioButtonBackground,
    //RadioButtonBorder,
    //RadioButtonPressedForeground,
    //RadioButtonPressedBackground,
    //RadioButtonPressedBorder,
    //RadioButtonMouseOverForeground,
    //RadioButtonMouseOverBackground,
    //RadioButtonMouseOverBorder,

    BasicGreyButtonForeground,
    BasicGreyButtonBackground,
    BasicGreyButtonBorder,
    BasicGreyButtonMouseOverForeground,
    BasicGreyButtonMouseOverBackground,
    BasicGreyButtonMouseOverBorder,
    BasicGreyButtonPressedForeground,
    BasicGreyButtonPressedBackground,
    BasicGreyButtonPressedBorder,

    BlueButtonForeground,
    BlueButtonBackground,
    BlueButtonBorder,
    BlueButtonMouseOverForeground,
    BlueButtonMouseOverBackground,
    BlueButtonMouseOverBorder,
    BlueButtonPressedForeground,
    BlueButtonPressedBackground,
    BlueButtonPressedBorder,

    LightBlueButtonForeground,
    LightBlueButtonBackground,
    LightBlueButtonBorder,
    LightBlueButtonMouseOverForeground,
    LightBlueButtonMouseOverBackground,
    LightBlueButtonMouseOverBorder,
    LightBlueButtonPressedForeground,
    LightBlueButtonPressedBackground,
    LightBlueButtonPressedBorder,
  }
}
